Feat/safety features
luxonis/datadreamer pull request #63
Opened 2024-09-30 03:57 UTC by HonzaCuhel

This PR adds the following functionality:
- Checking user input (`class_names` against list of bad words).
- Checking generated LM prompt against list of bad words and prompting a SLM whether the text is safe or not.
- Updated requirements and tests.

As the SLM, the latest Qwen2.5 with 0.5B was chosen for its small size and performance.

2024-09-30 10:27 UTC, klemen1999 approved these changes
LGTM

2024-10-07 14:12 UTC, sokovninn requested changes
Looks good overall, left some comments.

2024-10-07 14:12 UTC, sokovninn commented on datadreamer/prompt_generation/profanity_filter.py
> +        model_name = "Qwen/Qwen2.5-1.5B-Instruct"
Let's add some model initialization logging info here, just like with other models, since this is usually the most time-consuming part.

2024-10-07 14:12 UTC, sokovninn commented on datadreamer/prompt_generation/profanity_filter.py
> +                return response.lower().strip() == "appropriate"
Can we expect the language model to always return the answer in exactly this form?

2024-10-07 14:12 UTC, sokovninn commented on datadreamer/prompt_generation/profanity_filter.py
> +            model_name, torch_dtype="auto", device_map=self.device
CPU and CUDA initialization isn't different here, right? (like in prompt generators)

2024-10-07 14:36 UTC, HonzaCuhel commented on README.md
> +- `--use_only_bad_words_filter`: Use only a bad word list for profanity filtering. Default is `False`.
Yeah, that's better name for the argument!

2024-10-07 15:33 UTC, sokovninn approved these changes

2024-10-07 15:35 UTC, merged